# Generated by Django 5.1.6 on 2025-02-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('person_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('debit', models.FloatField(default=0.0)),
                ('total_sales', models.IntegerField(default=0)),
                ('gst', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InwardInvoiceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('final_amount', models.FloatField()),
                ('product_list', models.ManyToManyField(to='inventory.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inward_supply.supplier')),
            ],
        ),
    ]
