# Generated by Django 5.1.6 on 2025-03-22 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward_supply', '0002_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicebill',
            name='retailer_name',
        ),
        migrations.AddField(
            model_name='invoicebill',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inward_supply.supplier'),
        ),
    ]
