# Generated by Django 5.1.6 on 2025-03-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inward_supply', '0002_inwardinvoicebill_user_supplier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='gst',
        ),
    ]
