# Generated by Django 5.1.6 on 2025-03-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inward_supply', '0003_remove_supplier_gst'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InwardInvoiceBill',
        ),
    ]
