# Generated by Django 5.1.6 on 2025-03-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward_supply', '0003_remove_invoicebill_retailer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='amount',
            field=models.FloatField(),
        ),
    ]
