# Generated by Django 5.1.6 on 2025-03-24 13:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inward_supply', '0006_alter_invoicebill_bill_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoicebill',
            unique_together={('user', 'bill_number')},
        ),
    ]
