# Generated by Django 5.1.7 on 2025-04-01 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inward_supply", "0008_alter_supplier_total_sales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="phone_number",
            field=models.CharField(
                max_length=10,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
    ]
