# Generated by Django 5.1.7 on 2025-04-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward_supply', '0010_alter_supplier_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
