# Generated by Django 5.1.6 on 2025-02-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=50, unique=True)),
                ('sales_price', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('MRP', models.FloatField()),
                ('gst', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('profit', models.FloatField()),
                ('total_quantity_sold', models.IntegerField(default=0)),
            ],
        ),
    ]
