# Generated by Django 5.1.5 on 2025-02-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='mrp',
            new_name='max_retail_price',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='qty',
            new_name='quantity',
        ),
    ]
