# Generated by Django 5.1.6 on 2025-03-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('inward_supply', '0004_delete_inwardinvoicebill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
