# Generated by Django 5.1.6 on 2025-03-24 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_mrp_inventory_max_retail_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('user', 'item_id')},
        ),
    ]
