# Generated by Django 5.0.6 on 2025-03-25 12:42

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='unique_user_item_id',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='gst',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99.99'))]),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('user', 'item_id')},
        ),
    ]
