# Generated by Django 5.1.4 on 2025-03-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='add_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
