# Generated by Django 5.1.7 on 2025-04-05 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outward_supply', '0008_alter_retailer_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='retailer',
            unique_together={('user', 'firm_name')},
        ),
    ]
