# Generated by Django 5.1.7 on 2025-04-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outward_supply', '0009_alter_retailer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
