# Generated by Django 5.1.6 on 2025-04-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_address_alter_profile_firm_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='GST_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
